service: wealth-atlas-sync

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: ${self:service}-${self:provider.stage}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - !GetAtt SyncTable.Arn

package:
  patterns:
    - '!node_modules/**'
    - '!src/**'
    - '!test-*'
    - '!*.md'
    - '!.git/**'
    - '!.github/**'
    - '!.serverless/**'
    - 'dist/handler.js'

functions:
  sync:
    handler: dist/handler.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /data
          method: post
          cors: true
      - http:
          path: /data
          method: options
          cors: true
      - http:
          path: /data/{keyId}
          method: get
          cors: true
      - http:
          path: /data/{keyId}
          method: put
          cors: true
      - http:
          path: /data/{keyId}
          method: delete
          cors: true
      - http:
          path: /data/{keyId}
          method: options
          cors: true

resources:
  Resources:
    SyncTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: keyId
            AttributeType: S
        KeySchema:
          - AttributeName: keyId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

  Outputs:
    ApiEndpoint:
      Description: "API Gateway endpoint URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: "ApiGatewayRestApi"
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
    TableName:
      Description: "DynamoDB Table Name"
      Value: ${self:service}-${self:provider.stage}
