service: wealth-atlas-sync

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: wealth-atlas-sync-${self:provider.stage}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

plugins:
  - serverless-plugin-typescript

functions:
  sync:
    handler: src/handler.main
    events:
      - http:
          path: /data
          method: post
          cors: true
      - http:
          path: /data/{keyId}
          method: get
          cors: true
      - http:
          path: /data/{keyId}
          method: put
          cors: true
      - http:
          path: /data/{keyId}
          method: delete
          cors: true

resources:
  Resources:
    SyncTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wealth-atlas-sync-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: keyId
            AttributeType: S
        KeySchema:
          - AttributeName: keyId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  Outputs:
    ApiEndpoint:
      Description: "API Gateway endpoint URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: "ApiGatewayRestApi"
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
    TableName:
      Description: "DynamoDB Table Name"
      Value: wealth-atlas-sync-${self:provider.stage}
